#!/bin/bash

create_initramfs()
{
 sudo mkinitramfs -o /boot/init.gz

 if ! grep -q "^initramfs " /boot/config.txt; then
  echo initramfs init.gz | sudo tee -a /boot/config.txt > /dev/null 2>&1
 fi

 if ! grep -q "^overlay" /etc/initramfs-tools/modules; then
  echo overlay | sudo tee -a /etc/initramfs-tools/modules > /dev/null 2>&1
 fi
}
echo creating initramfs ; create_initramfs
