#!/bin/bash
rw_script()
{
sudo bash -c 'cat > /home/pi/rw-mode' << 'EOL'
#!/bin/bash

sudo mount -o remount,rw /mnt/root-ro
sudo touch /mnt/root-ro/disable-root-ro
sudo reboot
EOL
sudo chmod +x /home/pi/rw-mode
}
echo creating rw script ; rw_script
