#!/bin/bash

disable_swap()
{
 sudo dphys-swapfile swapoff
 sudo dphys-swapfile uninstall
 sudo update-rc.d dphys-swapfile disable
 sudo /lib/systemd/systemd-sysv-install disable dphys-swapfile
}
echo disabling swap ; disable_swap
