#!/bin/bash
update_initramfs()
{
 sudo update-initramfs -u
 sudo mkinitramfs -o /boot/init.gz

 if ! grep -q "root-ro-driver=overlay" /boot/cmdline.txt; then
  sudo sed -i "1 s|$| root-ro-driver=overlay|" /boot/cmdline.txt
 fi
}
echo updating initramfs ; update_initramfs
